; Create an empty array for the dictionary
dictionary := []

; Add words to the dictionary using Push (Original List)
dictionary.Push("apple")
dictionary.Push("orange")
dictionary.Push("banana")
dictionary.Push("grape")
dictionary.Push("peach")
dictionary.Push("melon")
dictionary.Push("berry")
dictionary.Push("plum")
dictionary.Push("kiwi")
dictionary.Push("lemon")
dictionary.Push("mango")
dictionary.Push("papaya")
dictionary.Push("coconut")
dictionary.Push("apricot")
dictionary.Push("fig")
dictionary.Push("date")
dictionary.Push("lime")
dictionary.Push("nectar")
dictionary.Push("jackson")
dictionary.Push("oliver")
dictionary.Push("sophia")
dictionary.Push("mason")
dictionary.Push("isabella")
dictionary.Push("liam")
dictionary.Push("ava")
dictionary.Push("noah")
dictionary.Push("mia")
dictionary.Push("elijah")
dictionary.Push("harper")
dictionary.Push("james")
dictionary.Push("evelyn")
dictionary.Push("willow")
dictionary.Push("lucas")
dictionary.Push("scarlett")
dictionary.Push("michael")
dictionary.Push("amelia")
dictionary.Push("benjamin")
dictionary.Push("layla")
dictionary.Push("ethan")
dictionary.Push("chloe")
dictionary.Push("alex")
dictionary.Push("aaron")
dictionary.Push("charlie")
dictionary.Push("abigail")
dictionary.Push("zoe")
dictionary.Push("henry")
dictionary.Push("natalie")
dictionary.Push("ryan")
dictionary.Push("madison")
dictionary.Push("victor")
dictionary.Push("grace")
dictionary.Push("taylor")
dictionary.Push("brody")
dictionary.Push("leah")
dictionary.Push("luna")
dictionary.Push("ashton")
dictionary.Push("cora")
dictionary.Push("victoria")
dictionary.Push("elena")
dictionary.Push("max")
dictionary.Push("zoey")
dictionary.Push("daisy")
dictionary.Push("logan")
dictionary.Push("riley")
dictionary.Push("amaya")
dictionary.Push("jaxon")
dictionary.Push("maddox")
dictionary.Push("dylan")
dictionary.Push("mabel")
dictionary.Push("aiden")
dictionary.Push("hannah")
dictionary.Push("lucy")
dictionary.Push("emily")
dictionary.Push("lola")
dictionary.Push("stella")
dictionary.Push("emilia")
dictionary.Push("ariel")
dictionary.Push("simon")
dictionary.Push("nina")
dictionary.Push("chris")
dictionary.Push("jenny")
dictionary.Push("ross")
dictionary.Push("monica")
dictionary.Push("joey")
dictionary.Push("phoebe")
dictionary.Push("rachel")
dictionary.Push("chandler")
dictionary.Push("yuna")
dictionary.Push("karen")
dictionary.Push("shawn")
dictionary.Push("clark")
dictionary.Push("kara")
dictionary.Push("alexa")
dictionary.Push("cameron")
dictionary.Push("brooke")
dictionary.Push("melody")
dictionary.Push("laura")
dictionary.Push("jordan")
dictionary.Push("mila")
dictionary.Push("theo")
dictionary.Push("isla")
dictionary.Push("piper")
dictionary.Push("laine")
dictionary.Push("tatum")
dictionary.Push("simon")
dictionary.Push("kaitlyn")
dictionary.Push("lance")
dictionary.Push("penny")
dictionary.Push("flora")
dictionary.Push("fiona")
dictionary.Push("eric")
dictionary.Push("sasha")
dictionary.Push("aurora")
dictionary.Push("diana")
dictionary.Push("frank")
dictionary.Push("helen")
dictionary.Push("cindy")
dictionary.Push("gordon")
dictionary.Push("olga")
dictionary.Push("quinn")
dictionary.Push("mabel")
dictionary.Push("poppy")
dictionary.Push("sienna")
dictionary.Push("marcus")
dictionary.Push("margo")
dictionary.Push("rain")
dictionary.Push("hunter")
dictionary.Push("marley")
dictionary.Push("onion")
dictionary.Push("garlic")
dictionary.Push("pepper")
dictionary.Push("spinach")
dictionary.Push("lettuce")
dictionary.Push("tomato")
dictionary.Push("potato")
dictionary.Push("zucchini")
dictionary.Push("pumpkin")
dictionary.Push("broccoli")
dictionary.Push("cauliflower")
dictionary.Push("asparagus")
dictionary.Push("eggplant")
dictionary.Push("turnip")
dictionary.Push("squash")
dictionary.Push("beet")
dictionary.Push("artichoke")
dictionary.Push("corn")
dictionary.Push("parsley")
dictionary.Push("basil")
dictionary.Push("cilantro")
dictionary.Push("chive")
dictionary.Push("thyme")
dictionary.Push("rosemary")
dictionary.Push("sage")
dictionary.Push("tarragon")
dictionary.Push("dill")
dictionary.Push("vanilla")
dictionary.Push("cinnamon")
dictionary.Push("ginger")
dictionary.Push("clove")
dictionary.Push("nutmeg")
dictionary.Push("peppermint")
dictionary.Push("walnut")
dictionary.Push("hazelnut")
dictionary.Push("chestnut")
dictionary.Push("almond")
dictionary.Push("pecan")
dictionary.Push("macadamia")
dictionary.Push("cashew")
dictionary.Push("sunflower")
dictionary.Push("pumpkin")
dictionary.Push("sesame")
dictionary.Push("chia")
dictionary.Push("flax")
dictionary.Push("cumin")
dictionary.Push("coriander")
dictionary.Push("mustard")
dictionary.Push("horseradish")
dictionary.Push("curry")
dictionary.Push("saffron")
dictionary.Push("quinoa")
dictionary.Push("bulgur")
dictionary.Push("barley")
dictionary.Push("oatmeal")
dictionary.Push("rye")
dictionary.Push("spelt")
dictionary.Push("wheat")
dictionary.Push("rice")
dictionary.Push("soba")
dictionary.Push("udon")
dictionary.Push("noodle")
dictionary.Push("pasta")
dictionary.Push("baguette")
dictionary.Push("croissant")
dictionary.Push("pita")
dictionary.Push("tortilla")
dictionary.Push("lavash")
dictionary.Push("focaccia")
dictionary.Push("ciabatta")
dictionary.Push("biscuit")
dictionary.Push("crouton")
dictionary.Push("muffin")
dictionary.Push("cookie")
dictionary.Push("brownie")
dictionary.Push("cake")
dictionary.Push("pie")
dictionary.Push("tart")
dictionary.Push("pudding")
dictionary.Push("gelato")
dictionary.Push("sorbet")
dictionary.Push("icecream")
dictionary.Push("chocolate")
dictionary.Push("candy")
dictionary.Push("jelly")
dictionary.Push("marshmallow")
dictionary.Push("caramel")
dictionary.Push("fudge")
dictionary.Push("syrup")
dictionary.Push("whipped")
dictionary.Push("cream")
dictionary.Push("butter")
dictionary.Push("margarine")
dictionary.Push("mayonnaise")
dictionary.Push("salsa")
dictionary.Push("ketchup")
dictionary.Push("mustard")
dictionary.Push("vinegar")
dictionary.Push("sauce")
dictionary.Push("olive")
dictionary.Push("peanut")
dictionary.Push("soy")
dictionary.Push("almond")
dictionary.Push("coconut")
dictionary.Push("sunflower")
dictionary.Push("sesame")
dictionary.Push("walnut")
dictionary.Push("pecan")
dictionary.Push("hazelnut")
dictionary.Push("chocolate")
dictionary.Push("berry")
dictionary.Push("vanilla")
dictionary.Push("mint")
dictionary.Push("jalapeno")
dictionary.Push("pimento")
dictionary.Push("pepperoni")
dictionary.Push("salami")
dictionary.Push("sausage")
dictionary.Push("bacon")
dictionary.Push("ham")
dictionary.Push("beef")
dictionary.Push("chicken")
dictionary.Push("turkey")
dictionary.Push("fish")
dictionary.Push("tuna")
dictionary.Push("salmon")
dictionary.Push("cod")
dictionary.Push("crab")
dictionary.Push("shrimp")
dictionary.Push("scallop")
dictionary.Push("lobster")
dictionary.Push("clam")
dictionary.Push("oyster")
dictionary.Push("squid")
dictionary.Push("octopus")
dictionary.Push("tofu")
dictionary.Push("tempeh")
dictionary.Push("seitan")
dictionary.Push("pork")
dictionary.Push("lamb")
dictionary.Push("venison")
dictionary.Push("duck")
dictionary.Push("goose")
dictionary.Push("quail")
dictionary.Push("rabbit")
dictionary.Push("frog")
dictionary.Push("venison")
dictionary.Push("squid")
dictionary.Push("turtle")
dictionary.Push("carp")
dictionary.Push("bass")

; Add new words (Adjectives)
dictionary.Push("quick")
dictionary.Push("brilliant")
dictionary.Push("creative")
dictionary.Push("mysterious")
dictionary.Push("bold")
dictionary.Push("energetic")
dictionary.Push("friendly")
dictionary.Push("honest")
dictionary.Push("elegant")
dictionary.Push("graceful")
dictionary.Push("radiant")
dictionary.Push("diligent")
dictionary.Push("innovative")
dictionary.Push("ambitious")
dictionary.Push("determined")
dictionary.Push("fearless")
dictionary.Push("charming")
dictionary.Push("witty")
dictionary.Push("brave")
dictionary.Push("adventurous")
dictionary.Push("cheerful")
dictionary.Push("curious")
dictionary.Push("fierce")
dictionary.Push("passionate")
dictionary.Push("thoughtful")
dictionary.Push("intelligent")
dictionary.Push("insightful")
dictionary.Push("delightful")
dictionary.Push("sophisticated")
dictionary.Push("playful")
dictionary.Push("vibrant")
dictionary.Push("calm")
dictionary.Push("serene")
dictionary.Push("zealous")
dictionary.Push("stunning")
dictionary.Push("exciting")

; Add names of famous actors
dictionary.Push("Leonardo DiCaprio")
dictionary.Push("Angelina Jolie")
dictionary.Push("Tom Hanks")
dictionary.Push("Meryl Streep")
dictionary.Push("Robert Downey Jr.")
dictionary.Push("Jennifer Lawrence")
dictionary.Push("Denzel Washington")
dictionary.Push("Scarlett Johansson")
dictionary.Push("Brad Pitt")
dictionary.Push("Julia Roberts")
dictionary.Push("Morgan Freeman")
dictionary.Push("Kate Winslet")
dictionary.Push("Johnny Depp")
dictionary.Push("Emma Stone")
dictionary.Push("Hugh Jackman")
dictionary.Push("Natalie Portman")
dictionary.Push("Chris Hemsworth")
dictionary.Push("Charlize Theron")
dictionary.Push("Matthew McConaughey")
dictionary.Push("Halle Berry")
dictionary.Push("Ryan Reynolds")
dictionary.Push("Anne Hathaway")
dictionary.Push("Ben Affleck")
dictionary.Push("Nicole Kidman")
dictionary.Push("Will Smith")
dictionary.Push("Jason Momoa")
dictionary.Push("Robert Pattinson")
dictionary.Push("Margot Robbie")
dictionary.Push("Ryan Gosling")
dictionary.Push("Jessica Chastain")
dictionary.Push("Samuel L. Jackson")

; Add titles of movies
dictionary.Push("The Lion King")
dictionary.Push("Gladiator")
dictionary.Push("Avatar")
dictionary.Push("The Shawshank Redemption")
dictionary.Push("Jurassic Park")
dictionary.Push("The Godfather")
dictionary.Push("Casablanca")
dictionary.Push("Schindler's List")
dictionary.Push("The Silence of the Lambs")
dictionary.Push("The Wizard of Oz")
dictionary.Push("Gone with the Wind")
dictionary.Push("Forrest Gump")
dictionary.Push("Braveheart")
dictionary.Push("The Avengers")
dictionary.Push("Titanic")
dictionary.Push("Spider-Man")
dictionary.Push("E.T. the Extra-Terrestrial")
dictionary.Push("Pulp Fiction")
dictionary.Push("The Matrix")
dictionary.Push("Fight Club")
dictionary.Push("Inception")
dictionary.Push("La La Land")
dictionary.Push("The Dark Knight")
dictionary.Push("Interstellar")
dictionary.Push("Black Panther")
dictionary.Push("Joker")
dictionary.Push("Parasite")
dictionary.Push("Mad Max: Fury Road")
dictionary.Push("The Wolf of Wall Street")
dictionary.Push("Frozen")
dictionary.Push("The Incredibles")
dictionary.Push("Finding Nemo")
dictionary.Push("Toy Story")
dictionary.Push("Coco")
dictionary.Push("Inside Out")
dictionary.Push("Moana")
dictionary.Push("The Shape of Water")
dictionary.Push("Lady Bird")
dictionary.Push("Moonlight")
dictionary.Push("A Star Is Born")
dictionary.Push("Dune")
dictionary.Push("Everything Everywhere All at Once")

; Add titles of famous books
dictionary.Push("To Kill a Mockingbird")
dictionary.Push("1984")
dictionary.Push("Pride and Prejudice")
dictionary.Push("Moby Dick")
dictionary.Push("The Great Gatsby")
dictionary.Push("Harry Potter")
dictionary.Push("The Catcher in the Rye")
dictionary.Push("Lord of the Rings")
dictionary.Push("Brave New World")
dictionary.Push("The Hobbit")
dictionary.Push("War and Peace")
dictionary.Push("The Odyssey")
dictionary.Push("Crime and Punishment")
dictionary.Push("Fahrenheit 451")
dictionary.Push("Wuthering Heights")
dictionary.Push("The Chronicles of Narnia")
dictionary.Push("Anna Karenina")
dictionary.Push("Jane Eyre")
dictionary.Push("The Count of Monte Cristo")
dictionary.Push("The Alchemist")
dictionary.Push("The Grapes of Wrath")
dictionary.Push("Catch-22")
dictionary.Push("Great Expectations")
dictionary.Push("The Picture of Dorian Gray")
dictionary.Push("The Bell Jar")
dictionary.Push("The Handmaid's Tale")
dictionary.Push("Little Women")
dictionary.Push("The Road")
dictionary.Push("Life of Pi")
dictionary.Push("The Fault in Our Stars")
dictionary.Push("The Kite Runner")
dictionary.Push("Educated")
dictionary.Push("Where the Crawdads Sing")
dictionary.Push("The Night Circus")
dictionary.Push("The Silent Patient")

; Add more verbs
dictionary.Push("run")
dictionary.Push("jump")
dictionary.Push("fly")
dictionary.Push("create")
dictionary.Push("explore")
dictionary.Push("imagine")
dictionary.Push("build")
dictionary.Push("sing")
dictionary.Push("dance")
dictionary.Push("read")
dictionary.Push("write")
dictionary.Push("speak")
dictionary.Push("listen")
dictionary.Push("code")
dictionary.Push("learn")
dictionary.Push("teach")
dictionary.Push("drive")
dictionary.Push("play")
dictionary.Push("paint")
dictionary.Push("cook")
dictionary.Push("bake")
dictionary.Push("swim")
dictionary.Push("climb")
dictionary.Push("dream")
dictionary.Push("discover")
dictionary.Push("analyze")
dictionary.Push("organize")
dictionary.Push("negotiate")
dictionary.Push("create")
dictionary.Push("motivate")
dictionary.Push("inspire")
dictionary.Push("collaborate")
dictionary.Push("celebrate")
dictionary.Push("challenge")
dictionary.Push("advocate")
dictionary.Push("facilitate")
dictionary.Push("support")
dictionary.Push("validate")
dictionary.Push("transform")
dictionary.Push("eliminate")
dictionary.Push("prioritize")
dictionary.Push("encourage")
dictionary.Push("reflect")
dictionary.Push("persevere")
dictionary.Push("succeed")
dictionary.Push("thrive")

; Set a flag for the toggle
isRunning := false

; Initialize click coordinates
clickX := ""
clickY := ""

; Show initial message to set click coordinates
MsgBox, Put your mouse on the position of the search bar and press Alt + 1

; Hotkey to set the click coordinates (Alt + 1)
!1::
    MouseGetPos, clickX, clickY  ; Get the current mouse position
    ToolTip, Click coordinates set. Press Alt + M to start the search
    Sleep, 2000
    ToolTip  ; Clear the tooltip
return

; Hotkey to toggle the search (Alt + M)
!m::  ; Alt + M
    if (clickX = "" || clickY = "") {
        ToolTip, Please set the click coordinates first by pressing Alt + 1.
        Sleep, 2000
        ToolTip  ; Clear the tooltip
        return
    }
    isRunning := !isRunning
    if (isRunning) {
        ; Start the search loop
        SetTimer, SearchLoop, 2000  ; Set the timer to 2 seconds (minimum)
        ToolTip, Random search started. Press Alt + M to stop.
    } else {
        ; Stop the search loop
        SetTimer, SearchLoop, Off
        ToolTip, Random search stopped. Press Alt + M to start again.
    }
    Sleep, 2000
    ToolTip  ; Clear the tooltip
return

SearchLoop:
    ; Randomly decide how many words to select (2 to 5)
    Random, wordCount, 2, 5
    searchWords := ""

    ; Select the specified number of random words
    Loop, %wordCount%
    {
        Random, index, 1, dictionary.MaxIndex()
        searchWords .= dictionary[index] " "  ; Concatenate the words with spaces
    }

    ; Click at the specified position
    Click, %clickX%, %clickY%

    ; Clear the text box
    Send, ^a  ; Select all text (Ctrl + A)
    Sleep, 100
    Send, {Del}  ; Delete selected text

    ; Send the random words to the text box
    Send, %searchWords%{Enter}

    ; Random sleep between 3 to 7 seconds
    Random, sleepTime, 3000, 7000
    Sleep, %sleepTime%
return
